// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
........................
.....ffff...............
...fff22fff.............
..fff2222fff............
.fffeeeeeefff...........
.ffe222222eef...........
.fe2ffffff2ef...........
.ffffeeeeffff...........
ffefbf44fbfeff..........
fee41fddf14eef..........
.ffffdddddeef...........
fddddf444eef............
fbbbbf2222f4e...........
fbbbbf2222fd4...........
.fccf45544f44...........
..ffffffff..............
....ff..ff..............
........................
........................
........................
........................
........................
........................
........................
`;
            case "image2":
            case "myImage0":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . c c . . . . . . 
. . . . . . . c 5 c . . . . . . 
. . . . c c c 5 5 c c c . . . . 
. . c c b c 5 5 5 5 c c c c . . 
. c b b 5 b 5 5 5 5 b 5 b b c . 
. c b 5 5 b b 5 5 b b 5 5 b c . 
. . f 5 5 5 b b b b 5 5 5 c . . 
. . f f 5 5 5 5 5 5 5 5 f f . . 
. . f f f b f e e f b f f f . . 
. . f f f 1 f b b f 1 f f f . . 
. . . f e e e b b b b f f . . . 
. . . e b b e e e e f b b e . . 
. . . e b b e b b 5 5 f e e . . 
. . . . c e e 5 5 5 5 5 f . . . 
. . . . . f f f f f f f . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
